--soal no 1
SELECT * FROM "T_POLICY" po 
JOIN "T_CLIENT" cl ON cl."CLIENT_NUMBER" = po."CLIENT_NUMBER" 
WHERE po."POLICY_SUBMIT_DATE" > '1/15/2018' AND EXTRACT(MONTH FROM cl."BIRTH_DATE") = 9;

--soal no 2
SELECT * FROM "T_POLICY" po 
JOIN "T_AGENT" ag ON ag."AGENT_CODE" = po."AGENT_CODE" 
WHERE po."POLICY_STATUS" = 'INFORCE' AND ag."AGENT_OFFICE" = 'JAKARTA';

--soal no 3
SELECT
	((po."COMMISSION" / po."PREMIUM") * 100) AS "BASIC_COMMISSION"
FROM
	"T_POLICY" po
JOIN
	"T_AGENT" ag ON ag."AGENT_CODE" = po."AGENT_CODE"
WHERE ag."AGENT_CODE" = po."AGENT_CODE"

--soal no 4
UPDATE "T_POLICY"
SET "POLICY_DUE_DATE" = DATE_TRUNC('MONTH', "POLICY_SUBMIT_DATE") + INTERVAL '30 DAYS' + INTERVAL '1 MONTH' - INTERVAL '1 DAY'

--soal no 5
SELECT * FROM "T_AGENT" ag
JOIN "T_POLICY" po ON po."AGENT_CODE" = ag."AGENT_CODE"
WHERE (po."PREMIUM" - ((po."PREMIUM" * po."DISCOUNT") / 100)) < '$1000000'
ORDER BY po."PREMIUM" ASC